name: check

on:
  push:
    branches:
      - 'main'


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          bin/build.sh
      - name: Check
        run: |
          bin/check.sh
