name: test

on:
  push:
    branches:
      - '*'


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          bin/build.sh
      - name: Unit tests
        run: |
          bin/test-unit.sh
