name: test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          bin/build.sh
      - name: Unit tests
        run: |
          bin/test-unit.sh
      - name: Integration tests
        run: |
