name: test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          bin/build.sh
      - name: Unit tests
        run: |
          bin/test-unit.sh
      - name: Integration tests
        run: |
          VERSION=4.2.0
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/${VERSION}/hurl_${VERSION}_amd64.deb
          sudo apt update && sudo apt install ./hurl_4.2.0_amd64.deb
          bin/integration.sh
