name: test

on:
  push:
    branches:
      - 'main'


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          bin/build.sh
      - name: Unit tests
        run: |
          bin/test-unit.sh
      - name: Integration tests
        run: |
          curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/1.7.0/hurl_1.7.0_amd64.deb
          sudo dpkg -i hurl_1.7.0_amd64.deb
          bin/integration.sh
