name: test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          bin/build.sh
      - name: Unit tests
        run: |
          bin/test-unit.sh
      - name: Integration tests
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/$VERSION/hurl_4.3.0_amd64.deb
          sudo apt update && sudo apt install ./hurl_4.3.0_amd64.deb
          bin/integration.sh
